- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  tasks:
  - name: print username
    ansible.builtin.debug:
      msg: "Username is: {{ username }}"