- name: Gathering ansible facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"   # facts contain all information about target server. Here ansible_facts is reserved variable.
