- name: Install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Installing package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: "nginx", state: "latest" }
      - { name: "zip", state: "absent" }
      - { name: "mysql", state: "absent" }
