---
- name: Installing httpd and php on all app servers
  hosts: "app-servers"
  become: yes

  vars:
    http_port: 8089

  tasks:
  - name: Install httpd
    ansible.builtin.package:
      name: httpd
      state: present
  
  - name: Configure Apache to listen on custom port
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      line: "Listen {{ http_port }}"
    
  - name: Start and enable httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Install PHP and common modules
    ansible.builtin.package:
      name:
        - php
        - php-cli
        - php-common
        - php-mysqlnd
        - php-fpm
      state: present

  - name: Start and enable PHP-FPM

    service:
      name: php-fpm
      state: started
      enabled: yes

